stages:
  us_fuelprice_df_checks:
    cmd: python /project/DataEngineering/python_files/us_fuelprice_df.py
    outs:
      - us_fuelprice_df.txt:
          checkpoint: true
          
  uk_fuelprice_df_checks:
    cmd: python /project/DataEngineering/python_files/uk_fuelprice_df.py
    outs:
      - uk_fuelprice_df.txt:
          checkpoint: true
          
  stock_price_checks:
    cmd: python /project/DataEngineering/python_files/stock_price.py
    outs:
      - stock_price.txt:
          checkpoint: true

  fuel_price_checks:
    cmd: python /project/DataEngineering/python_files/fuel_price.py
    outs:
      - fuel_price.txt:
          checkpoint: true
          
  us_diff_checks:
    cmd: python /project/DataEngineering/python_files/us_diff.py
    outs:
      - us_diff.txt:
          checkpoint: true
          
  us_info_checks:
    cmd: python /project/DataEngineering/python_files/us_info.py
    outs:
      - us_info.txt:
          checkpoint: true
