stages:
  game_results_checks:
    cmd: python /project/DataEngineering/python_files/Game_results.py
    outs:
      - game_results.txt:
          checkpoint: true

  Athlete_personal_information_checks:
    cmd: python /project/DataEngineering/python_files/Athlete_personal_information.py
    outs:
      - Athlete_personal_information.txt:
          checkpoint: true

  STK_tweets_checks:
    cmd: python /project/DataEngineering/python_files/STK_tweets.py
    outs:
      - STK_tweets.txt:
          checkpoint: true

  data_transformation_checks:
    cmd: python /project/DataEngineering/python_files/data_transformation.py
    outs:
      - data_transformation.txt:
          checkpoint: true

  write_into_database_checks:
    cmd: python /project/DataEngineering/python_files/write_into_database.py
    outs:
      - write_into_database.txt:
          checkpoint: true